### ISSUE TITLE
Why does nvcc-test.py use both CudaModule and CudaGlobal?

### ISSUE THREAD

**Issue by Cazadorro** [inducer/codepy#17]
I don't understand why it is necessary to use CudaGlobal in [nvcc-test.py](https://github.com/inducer/codepy/blob/master/test/nvcc-test.py), why can't we just add those functions to the CudaModule directly like we see [here](https://gist.github.com/bryancatanzaro/2772091)?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

Also, it looks like you're completely misunderstanding this: `CudaGlobal` is part of the C AST, `CudaModule` provides JIT functionality.
